[package]
name = "wasm-pvm"
description = "WASM to PVM (PolkaVM) recompiler"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
wasmparser.workspace = true
thiserror.workspace = true

[lints]
workspace = true
